language: java
before_install:
  - git config user.name "$GIT_NAME"
  - git config user.email "$GIT_EMAIL"
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GH_TOKEN:@github.com" > .git/credentials
  - gem install asciidoctor
install:
#TODO: build docs
- mvn --settings .settings.xml install -U -DskipTests=true -Dmaven.test.redirectTestOutputToFile=true
#- mvn --settings .settings.xml install -P docs -q -U -DskipTests=true -Dmaven.test.redirectTestOutputToFile=true
#- ./docs/src/main/asciidoc/ghpages.sh
script:
#TODO: run zookeeper on tests?
#TODO: change to deploy
- '[ "${TRAVIS_PULL_REQUEST}" != "false" ] || mvn --settings .settings.xml install -nsu -Dmaven.test.redirectTestOutputToFile=true'
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] || mvn --settings .settings.xml install -nsu -Dmaven.test.redirectTestOutputToFile=true'
env:
  global:
  - GIT_NAME="Spencer Gibb"
  - GIT_EMAIL=sgibb@pivotal.io
  - CI_DEPLOY_USERNAME=sgibb
  - secure: C0sQZDWIkR5mhsstNzOgZ9hzyixLqul2k+EqUda7dJFZaRup0PSAdvZBJ6Kf2s9YF6ovovNCHOr4gadCrg7PFDik78lpgiytvUCIyHgKNATD809azkaVFFQPFT1Hq/SMK0un37rl2BxLI//0bJCvVkTNs6sGJ10pcPUtGvD+t18=
